In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
l = [1, 2, 3, 4, 5, 6]

In [4]:
# Will convert list to array
np.array(l) 

array([1, 2, 3, 4, 5, 6])

In [5]:
l1 = [4,6,7,8, "akhil", 34.45, True]

In [6]:
a1 = np.array(l1)

In [7]:
a2 = np.array([[1, 2, 3], [4,5,6]])
a3 = np.array([[[1,2,3], [4,5,6], [7,8,9]]])

In [8]:
a1.ndim # Direction of Array

1

In [9]:
a2.ndim # Direction of Array

2

In [10]:
a3.ndim # Direction of Array

3

In [11]:
a1.size # Total no. of element

7

In [12]:
a3.size

9

In [13]:
# Shape of the Array 
a2.shape 

(2, 3)

In [14]:
# Generate random Int b/w [5 to 10]
np.random.randint(5, 10, (3, 4), )

array([[8, 9, 8, 7],
       [9, 5, 8, 7],
       [6, 8, 8, 5]])

In [15]:
# Generate 2nd Data 
np.random.randint(2, 50, (3, 4))

array([[37, 39, 10, 26],
       [41, 16,  9, 19],
       [33, 11, 19, 46]])

In [16]:
np.random.rand(2,3)

array([[0.77305155, 0.21965499, 0.49839804],
       [0.92634361, 0.27499808, 0.0492575 ]])

In [17]:
a4 = np.random.randn(4, 4)

In [18]:
a4

array([[ 1.08541851, -1.6656609 ,  0.1350528 , -0.54137101],
       [ 0.23893707, -0.16166756, -1.88501163,  0.13798251],
       [ 0.81811528, -0.57959301, -0.73347901,  1.06143951],
       [ 1.19037458,  0.48059298, -0.80507334, -0.26273337]])

In [19]:
a4.reshape(2, 8)

array([[ 1.08541851, -1.6656609 ,  0.1350528 , -0.54137101,  0.23893707,
        -0.16166756, -1.88501163,  0.13798251],
       [ 0.81811528, -0.57959301, -0.73347901,  1.06143951,  1.19037458,
         0.48059298, -0.80507334, -0.26273337]])

In [20]:
a4.reshape(8, 2)

array([[ 1.08541851, -1.6656609 ],
       [ 0.1350528 , -0.54137101],
       [ 0.23893707, -0.16166756],
       [-1.88501163,  0.13798251],
       [ 0.81811528, -0.57959301],
       [-0.73347901,  1.06143951],
       [ 1.19037458,  0.48059298],
       [-0.80507334, -0.26273337]])

In [21]:
a4.reshape(16, 1)

array([[ 1.08541851],
       [-1.6656609 ],
       [ 0.1350528 ],
       [-0.54137101],
       [ 0.23893707],
       [-0.16166756],
       [-1.88501163],
       [ 0.13798251],
       [ 0.81811528],
       [-0.57959301],
       [-0.73347901],
       [ 1.06143951],
       [ 1.19037458],
       [ 0.48059298],
       [-0.80507334],
       [-0.26273337]])

In [22]:
a4.reshape(2, -1) # Automaticaly detect the Shape -1 

array([[ 1.08541851, -1.6656609 ,  0.1350528 , -0.54137101,  0.23893707,
        -0.16166756, -1.88501163,  0.13798251],
       [ 0.81811528, -0.57959301, -0.73347901,  1.06143951,  1.19037458,
         0.48059298, -0.80507334, -0.26273337]])

In [23]:
a4.reshape(2, 2, 4) # Reshaping in 3D.

array([[[ 1.08541851, -1.6656609 ,  0.1350528 , -0.54137101],
        [ 0.23893707, -0.16166756, -1.88501163,  0.13798251]],

       [[ 0.81811528, -0.57959301, -0.73347901,  1.06143951],
        [ 1.19037458,  0.48059298, -0.80507334, -0.26273337]]])

In [24]:
a1

array(['4', '6', '7', '8', 'akhil', '34.45', 'True'], dtype='<U32')

In [25]:
a1[0]

'4'

In [26]:
a1[2:6]

array(['7', '8', 'akhil', '34.45'], dtype='<U32')

In [27]:
a1[2:6:2]

array(['7', 'akhil'], dtype='<U32')

In [28]:
a1[::-1]

array(['True', '34.45', 'akhil', '8', '7', '6', '4'], dtype='<U32')

In [29]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
a2[:,1:] # Getting the Matrix Data 

array([[2, 3],
       [5, 6]])

In [31]:
a2[:,[1,2 ]] # Getting the Matrix Data 

array([[2, 3],
       [5, 6]])

In [32]:
a2[[0,1],1:]

array([[2, 3],
       [5, 6]])

In [33]:
a5 = np.random.randint(2, 90, (6, 5))

In [34]:
a5

array([[72, 87, 68,  8, 66],
       [26, 32, 82,  8, 44],
       [35, 16, 59,  6, 22],
       [45,  7, 34, 85,  2],
       [33, 60, 62, 55, 14],
       [29, 58, 54, 59, 29]])

In [35]:
a5[a5>40]

array([72, 87, 68, 66, 82, 44, 59, 45, 85, 60, 62, 55, 58, 54, 59])

In [36]:
a5

array([[72, 87, 68,  8, 66],
       [26, 32, 82,  8, 44],
       [35, 16, 59,  6, 22],
       [45,  7, 34, 85,  2],
       [33, 60, 62, 55, 14],
       [29, 58, 54, 59, 29]])

In [37]:
a5[0,1] = 11

In [38]:
a5[0,1]

11

In [39]:
a6 = np.random.randint(0, 9, (3,3))
a6

array([[0, 0, 4],
       [7, 7, 4],
       [5, 5, 8]])

In [40]:
a7 = np.random.randint(0, 3, (3, 3))
a7

array([[2, 2, 2],
       [1, 1, 1],
       [1, 2, 2]])

In [41]:
a6 * a7 # Array element to element application 

array([[ 0,  0,  8],
       [ 7,  7,  4],
       [ 5, 10, 16]])

In [42]:
# Matrix multipication 
a6@a7

array([[ 4,  8,  8],
       [25, 29, 29],
       [23, 31, 31]])

In [43]:
a6 + 10

array([[10, 10, 14],
       [17, 17, 14],
       [15, 15, 18]])

In [44]:
a6/0

/tmp/ipykernel_33684/1058679823.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a6/0
/tmp/ipykernel_33684/1058679823.py:1: RuntimeWarning: invalid value encountered in true_divide
  a6/0


array([[nan, nan, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [45]:
a6**3

array([[  0,   0,  64],
       [343, 343,  64],
       [125, 125, 512]])

In [46]:
a8 = np.zeros((4, 4))
a8

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [47]:
a9 = np.ones((4, 5))
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [48]:
a9+10

array([[11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.]])

In [49]:
# Apply operation row whise
a9 + np.array([1, 2, 3, 4, 5])

array([[2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.]])

In [50]:
np.array([[1, 2, 3, 4]]).T

array([[1],
       [2],
       [3],
       [4]])

In [51]:
np.array([[1, 2, 3, 4]]).T + a9

array([[2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [52]:
a6.T

array([[0, 7, 5],
       [0, 7, 5],
       [4, 4, 8]])

In [53]:
np.sqrt(a6)

array([[0.        , 0.        , 2.        ],
       [2.64575131, 2.64575131, 2.        ],
       [2.23606798, 2.23606798, 2.82842712]])

In [54]:
np.exp(a6)

array([[1.00000000e+00, 1.00000000e+00, 5.45981500e+01],
       [1.09663316e+03, 1.09663316e+03, 5.45981500e+01],
       [1.48413159e+02, 1.48413159e+02, 2.98095799e+03]])

In [55]:
np.log2(a5)

array([[6.169925  , 3.45943162, 6.08746284, 3.        , 6.04439412],
       [4.70043972, 5.        , 6.357552  , 3.        , 5.45943162],
       [5.12928302, 4.        , 5.88264305, 2.5849625 , 4.45943162],
       [5.4918531 , 2.80735492, 5.08746284, 6.40939094, 1.        ],
       [5.04439412, 5.9068906 , 5.95419631, 5.78135971, 3.80735492],
       [4.857981  , 5.857981  , 5.7548875 , 5.88264305, 4.857981  ]])

In [56]:
list(range(1, 10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [57]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
# 50 numbers b/w the range of 2-3
np.linspace(2, 3, num=50)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [59]:
# Digonal Matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# CUFFLINKS, SEABORN 

In [64]:
pip install seaborn

Note: you may need to restart the kernel to use updated packages.


In [65]:
import cufflinks as cf
import numpy as np
import pandas as pd
import seaborn as sns 

In [66]:
cf.go_offline() 

In [214]:
df = pd.DataFrame(np.random.randn(100, 3), columns=['A', 'B', 'C'])
df

A         B         C
0  -0.193177  0.415018 -0.645015
1   0.130234 -0.007540  0.847782
2  -0.391971 -0.573358  0.502781
3  -0.089525  0.205604  0.167121
4   0.487394 -2.311211  0.565897
..       ...       ...       ...
95 -0.620175  0.299780 -0.707164
96 -0.425462  1.132793 -2.397263
97  0.086899  0.755726  0.591345
98  0.239820 -0.308010  2.687603
99  0.000236 -0.624676  1.898876

[100 rows x 3 columns]

In [215]:
df.iplot()

In [69]:
df = pd.DataFrame(np.random.randint(3, 10, (5, 5)))

In [71]:
df = pd.read_csv("/home/akhilesh/Downloads/FitBit data.csv")
df

Id ActivityDate  TotalSteps  TotalDistance  TrackerDistance  \
0    1503960366    3/25/2016       11004       7.110000         7.110000   
1    1503960366    3/26/2016       17609      11.550000        11.550000   
2    1503960366    3/27/2016       12736       8.530000         8.530000   
3    1503960366    3/28/2016       13231       8.930000         8.930000   
4    1503960366    3/29/2016       12041       7.850000         7.850000   
..          ...          ...         ...            ...              ...   
452  8877689391     4/8/2016       23014      20.389999        20.389999   
453  8877689391     4/9/2016       16470       8.070000         8.070000   
454  8877689391    4/10/2016       28497      27.530001        27.530001   
455  8877689391    4/11/2016       10622       8.060000         8.060000   
456  8877689391    4/12/2016        2350       1.780000         1.780000   

     LoggedActivitiesDistance  VeryActiveDistance  ModeratelyActiveDistance  \
0                         0.0                2.57                      0.46   
1                         0.0                6.92                      0.73   
2                         0.0                4.66                      0.16   
3                         0.0                3.19                      0.79   
4                         0.0                2.16                      1.09   
..                        ...                 ...                       ...   
452                       0.0               11.10                      0.63   
453                       0.0                0.00                      0.02   
454                       0.0               21.92                      1.12   
455                       0.0                1.47                      0.15   
456                       0.0                0.00                      0.00   

     LightActiveDistance  SedentaryActiveDistance  VeryActiveMinutes  \
0                   4.07                     0.00                 33   
1                   3.91                     0.00                 89   
2                   3.71                     0.00                 56   
3                   4.95                     0.00                 39   
4                   4.61                     0.00                 28   
..                   ...                      ...                ...   
452                 8.62                     0.00                 70   
453                 8.02                     0.00                 90   
454                 4.46                     0.00                128   
455                 6.37                     0.01                 18   
456                 1.78                     0.00                  0   

     FairlyActiveMinutes  LightlyActiveMinutes  SedentaryMinutes  Calories  
0                     12                   205               804      1819  
1                     17                   274               588      2154  
2                      5                   268               605      1944  
3                     20                   224              1080      1932  
4                     28                   243               763      1886  
..                   ...                   ...               ...       ...  
452                   29                   359               982      4196  
453                    9                   289              1052      3841  
454                   46                   211              1055      4526  
455                    7                   225              1190      2820  
456                    0                    58               531       938  

[457 rows x 15 columns]

In [72]:
df.iplot()

In [262]:
df = pd.DataFrame(np.random.randn(100,3), columns=["A", 'B', "C"])
df

A         B         C
0   1.180591 -1.176747  0.046381
1   0.940618 -0.271534  0.893965
2   0.237465 -0.969204  0.206768
3  -0.004230  0.307936 -0.065206
4   1.216538  0.218143 -0.133185
..       ...       ...       ...
95  1.121657  0.737663 -1.352968
96  0.135940  0.234254 -0.485545
97  0.327706 -0.004460 -1.220005
98 -0.911947  0.457810 -1.352919
99 -1.548264 -0.588398  1.280697

[100 rows x 3 columns]

In [270]:
df.iplot(x="A", mode="markers")

In [277]:
# Load CSV file from seaborn
df2 = sns.load_dataset("titanic")
df2

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [278]:
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [285]:
df2.iplot(x= "age", y="fare", mode= "markers")

In [286]:
df2.iplot(x= "age", y="pclass", mode= "markers")

In [289]:
df2.iplot(x= "fare", y="pclass", mode="markers")

In [290]:
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [301]:
df2.iplot(kind="bar", x="sex", y="survived")